### ISSUE TITLE
Extend info printed by `roc-vad info`

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-vad#7]
Current output looks like this:

```
roc-vad info
driver is loaded

driver:
  version: 0.0.1
  commit:  1b600b3

client:
  version: 0.0.3
  commit:  68aa992
```

In addition to driver info and client info, it would be nice to add build info:

* Xcode version used to build the binary
* macOS version used to build the binary
* macOS deployment target (CMAKE_OSX_DEPLOYMENT_TARGET)
* macOS target architectures (CMAKE_OSX_ARCHITECTURES)
* flag indicating whether the binary was built on github actions ([job](https://github.com/roc-streaming/roc-vad/blob/main/.github/workflows/build.yml#L56))

Also a few more fields would be useful in driver info:

* driver UUID
* driver bundle path
* driver socket

All this info should be added to `common/build_info.hpp` and then used in `tool/print.cpp`.
